### ISSUE TITLE
Important issue with raffle

### ISSUE THREAD

**Issue by mcdeimon** [VidYen/VYPS-Plugin#107]
When you buy a ticket and update the page you automatically buy another ticket even if you do not press the buy button.

**Comment by mcdeimon** [comment]
Hello Felty,

It seems that I have solved this by adding these lines in the file "vypstr.php" line "333"

`$new_url = add_query_arg( 'success', 1, get_permalink() );
wp_redirect( $new_url, 303 );`

Now if you reload the page, you do not buy a ticket automatically again.

**Comment by VidYen** [comment]
This has been fixed. Added the count check to make sure the post was on the same count as the actual game.

**Comment by mcdeimon** [comment]
Now another problem has appeared. When a user purchases a ticket and the page is reloaded, if the user presses the button again to buy a second ticket, the page is reloaded but the purchase is not made. You have to press a third time to buy the second ticket.
