### ISSUE TITLE
AJAX migration: Miner and PE on same page solution

### ISSUE THREAD

**Issue by VidYen** [VidYen/VYPS-Plugin#109]
With the 4doge, I realize that its annoying to have the entire page refresh. I would like a popup that's not a popup but a link to a target="_blank" with the post.

So...

https://wordpress.stackexchange.com/questions/274569/how-to-get-url-of-current-page-displayed

And...

https://stackoverflow.com/questions/896724/how-to-open-a-new-window-on-form-submit

I was thinking something along the lines of `target=new`

**Comment by VidYen** [comment]
After some deep thought today... I'm thinking of doing an ajax solution for the posts. I've been avoiding it as it **will** under no doubt break older browsers, but then VY256 isn't supposed to be run on older devices.

Also it will be less generic which was my goals, but I'm here wondering if I can stuff these into new windows and all sorts of bad looking stuff when I should just get over it and use AJAX.

**Comment by mcdeimon** [comment]
Regarding the integration of Ajax, could the two options be enabled? Ajax or not Ajax? In some plugin I have seen that option. For example, I do not have the miner on the same page as the PE. My PE is in the wallet section.

**Comment by VidYen** [comment]
I have mostly done this now that I realize with the new miner updates. PE will get its own plugin for the ajax solution.
