### ISSUE TITLE
User panel error

### ISSUE THREAD

**Issue by mcdeimon** [VidYen/VYPS-Plugin#117]
Hi Felty!!! 

In the admin panel, when I edit a user this error appears:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'custom_user_profile_fields_points' not found or invalid function name in /var/www/vhosts/bycryp.com/httpdocs/wp-includes/class-wp-hook.php on line 286

**Comment by mcdeimon** [comment]
![warning](https://user-images.githubusercontent.com/39587826/47415918-d71d4d00-d774-11e8-927e-c6990068446f.jpg)

**Comment by mcdeimon** [comment]
If I unplug the VYPS plugin the error disappears

**Comment by VidYen** [comment]
Had some spare time today... Looking at this... That func is found on lines 292, 293, 294....

```
add_action('show_user_profile', 'custom_user_profile_fields_points');
add_action('edit_user_profile', 'custom_user_profile_fields_points');
add_action("user_new_form", "custom_user_profile_fields_points");
```

(Side note... Not sure why " instead of ' there, but...)

This is on the edit user profile correct?

**Comment by VidYen** [comment]
I have replicated it. Ok. Will fix today if possible.

**Comment by VidYen** [comment]
Actually. It didn't take that long to fix as found the issue right away.

@mcdeimon please confirm the GitHub version works and it doesn't break anything else for you. I am going to upload this to WordPress as had saved some fixes to go in at least a slightly larger update.

**Comment by VidYen** [comment]
Whoops. Didn't commit. Now try if you did a minute ago.

**Comment by VidYen** [comment]
I went ahead and updated the official repo to 1.7.3 on WordPress. As I believe it was happening on everyone's system.

**Comment by VidYen** [comment]
Going to close this as I think it has been resolved (at least on my test sites)

**Comment by mcdeimon** [comment]
Thanks Felty!!! Now it works perfecty!
