### ISSUE TITLE
CP.net payout attribue

### ISSUE THREAD

**Issue by VidYen** [VidYen/VYPS-Plugin#64]
[Coinpayments](https://www.coinpayments.net/apidoc-create-withdrawal)

Now to scope creep VYPS, but it dawned on me you could have a payout that avoids WooCommerce all together. And have an API out.

In theory you could have an API in, but I'd rather we focus on browser mining for income. That is just me.

**Comment by VidYen** [comment]
`https://www.coinpayments.net/apidoc-create-withdrawal`

**Comment by CyberMutley** [comment]
API would be good.

If it can't be done yet, maybe having a Withdrawal option, and in the Admin Dashboard, have a list of withdrawals so the admin can process them manually.

**Comment by VidYen** [comment]
Good idea, but the more I think about how people have their WordPress security. Some one is going to have a bad day and get their CP account cleaned out when the WP site gets hacked.
