### ISSUE TITLE
Withdrawal Function

### ISSUE THREAD

**Issue by CyberMutley** [VidYen/VYPS-Plugin#66]
A feature suggestion

Using the plugin on my site an loving it so far.  A feature which I think would be good is allowing the users to have the ability to exchange into crypto if the site admin has a crypto setting enabled.  Then once the user has enough exchanged, he/she can then ask for a payout, which would then show up in the admin area (for example, on the dashboard), so the admin can process payouts manually.

1.  In the plugin settings, have a  crypto option.
2.  Have an exchange into crypto feature.
3.  Have a withdrawl option.
4.  Allow admins to manually process payments.

Thank you

**Comment by VidYen** [comment]
I think with the addition of the Dashed Slug Wallet, I think we can close this as his method is way better and I am tied into now.
