### ISSUE TITLE
Chat Plugin

### ISSUE THREAD

**Issue by CyberMutley** [VidYen/VYPS-Plugin#68]
Feature Suggestion

As the points plugin is to be used primarily for games etc, what would be a good feature is to have a supported chat plugin which will allow players to communicate with each other, just like many games out there have.

This feature can be used for many purposes as a lot of community websites have a chat function.  Maybe even adding point earning / spending using the chat could be an addon.

1.  Player / User chat room.
2.  Site admins can create different rooms (optional).
3.  Site admins can allow point earning or spending in the plugin admin.

Thank you

**Comment by VidYen** [comment]
I think everyone has their own chat now so would be reinventing the wheel at this point.

Also, maybe I should make hooks for Discord instead.
