### ISSUE TITLE
SUGGESTION - Premium Version

### ISSUE THREAD

**Issue by CyberMutley** [VidYen/VYPS-Plugin#81]
To help generate funds, I have a suggestion to adding a feature where an admin can choose to buy a Premium Version of the plugin.

Premium version could add extra functionality such as:-

1,  Removing the "Powered by" branding.
2,  Ability to change the sex of the miner from male to female.
3,  If possible, allow the use to choose the pool they wish to mine too.

You can as many feature as you can think off, and charge a fair amount for it.  Like I said, it would help you to fund other projects you have.

**Comment by VidYen** [comment]
2, That is already possible.  :)

**Comment by VidYen** [comment]
`graphic=`
0 = none
1 = male
2 = female

**Comment by VidYen** [comment]
I think we are going to stick with MO for now so closing. Otherwise rest is undocumented features.
